// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfaqILqYQy-Ea7H0h1V5EXrd7pqEEwKvQ',
    appId: '1:37665260435:web:ea78b7851eb87cf1355e66',
    messagingSenderId: '37665260435',
    projectId: 'study-app-e9c5e',
    authDomain: 'study-app-e9c5e.firebaseapp.com',
    storageBucket: 'study-app-e9c5e.appspot.com',
    measurementId: 'G-1PRQ652J56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvytUCf_Ojn55ol_-JSmNRsuicGvJZnZ4',
    appId: '1:37665260435:android:5b8bd76bc3e528c2355e66',
    messagingSenderId: '37665260435',
    projectId: 'study-app-e9c5e',
    storageBucket: 'study-app-e9c5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_peRzBoxdA7acO5hFRpz_9er8vj8s7wY',
    appId: '1:37665260435:ios:ec47878070e4e80b355e66',
    messagingSenderId: '37665260435',
    projectId: 'study-app-e9c5e',
    storageBucket: 'study-app-e9c5e.appspot.com',
    iosBundleId: 'com.example.studyApp',
  );
}
